### ISSUE TITLE
Liblitmus API with Paparazzi 

### ISSUE THREAD

**Issue by iAbdur18** [paparazzi/paparazzi-hardware#27]
Hi everyone,
so I am trying to obtain real-time data of Paparazzi built models and have recently installed Litmus RT Kernal of Ubuntu. I plan to treat each drone as a real-time task, i.e. a drone is created as a new real-time task.  This means I have to include the liblitmus API into the drone creation code in the paparazzi code. We don't want to run the whole Paparazzi as a single RT task. A more fine-grained wrap for the drone instances. 
Can someone guide me on this?

**Comment by gautierhattenberger** [comment]
closing as this is not an issue and not related to hardware
question answered in gitter channel
